apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobboard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/maxim-grin/homelab.git
    targetRevision: main
    path: argocd/apps/jobboard/dev
    plugin:
      name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: jobboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
